### PR TITLE
Scroll issue on ios. Scrolling does not go all the way down

### LINKED ISSUE #204: Scroll issue on ios. Scrolling does not go all the way down
https://user-images.githubusercontent.com/5694308/110075317-3532b400-7db5-11eb-845a-9f270ab5ac71.mp4

### PR DESCRIPTION
**Pull request by giteshk11**
Fixes #204

### CODE REVIEW

**Comment by weareminigolf** [comment]
Hi Gitesh!

It is getting better, the scroll is more fluid, but it seems the pop up seems to be aligned on the top of the page and not on the top of the footer and there still are issues with the background scrolling.



Sent from my iPhone

On 5 Mar 2021, at 22:38, Gitesh <notifications@github.com> wrote:

﻿

@giteshk11<https://github.com/giteshk11> requested your review on: #205<https://github.com/whynotearth/we-are-mini-golf-frontend/pull/205> Scroll issue on ios. Scrolling does not go all the way down.

**Comment by giteshk11** [comment]
@weareminigolf can you send me the screenshot and highlight inside that?

**Comment by weareminigolf** [comment]
I seems it is not going through there, I send the video on messenger

Sent from my iPhone

On 5 Mar 2021, at 23:22, Gitesh <notifications@github.com> wrote:

﻿

@weareminigolf<https://github.com/weareminigolf> can you send me the screenshot and highlight inside that?

**Comment by giteshk11** [comment]
@weareminigolf can you check it again? i've made some changes

**Review by paulchrisluke — APPROVED** [review]

**Comment by weareminigolf** [comment]
Got it.
Replied on messenger as I have trouble uploading videos here

Sent from my iPhone

On 6 Mar 2021, at 12:02, Paul Chris Luke <notifications@github.com> wrote:

﻿

@paulchrisluke approved this pull request.

**Pull request merged**
