### PR TITLE
created timeout modal, and updated some  button classes

### PR DESCRIPTION
**Pull request by freedannyv**
Timeout modal currently kicks in when the App.vue is created, and refreshes every 5s for testing purposes. I haven't been able to simply reset the timeout timer yet, so it goes off every 5s, which isn't ideal. I will continue to work on it tomorrow

### CODE REVIEW

**Review by paulchrisluke — APPROVED** [review]
ux approved pending code review to merge

**Comment by freedannyv** [comment]
<<<<<<< timeout-modal
        :to="{ name: getRouteName, params: { holeNo: holeNo + 1 } }"
        mode="btn confirm"
=======
        :to="{ name: 'NewHole', params: { holeNo: holeNo } }"
        mode="confirm"
>>>>>>> staging

This doesn't look like a change that I made.......?

**Comment by paulchrisluke** [comment]
@giteshk11 ^ ?

**Comment by giteshk11** [comment]
You can replace with your own code @freedannyv

**Comment by freedannyv** [comment]
Are you able to approve these changes @giteshk11 ?

**Pull request merged**
