### PR TITLE
[bug] player name input field does not show on initial load

### PR DESCRIPTION
**Pull request by giteshk11**
Fixes and for other screens also #84

### CODE REVIEW

**Comment by paulchrisluke** [comment]
I'm stuck on initial apo load it doesn't take me past the logo screen

**Comment by giteshk11** [comment]
@paulchrisluke try now

**Comment by freedannyv** [comment]
This is fixed in remove-x PR

**Comment by giteshk11** [comment]
https://6007e87281b76e9a6c9ff3f0--weareminigolf.netlify.app/ 
@paulchrisluke try the above link

**Review by paulchrisluke — APPROVED** [review]

**Pull request merged**
