### PR TITLE
Not all scores show on "current scores" drawer

### LINKED ISSUE #185: Not all scores show on "current scores" drawer
- [ ] NOT ALL SCORES SHOW
On a test I recorded scores for holes 1/2/3.
On the current score drawer, only results for holes 1 and 2 were recorded.

- [x] SCROLLING ISSUE
If I try to scroll in the white frame of the drawer, it first scrolls the background (in the video attached the navigation path) and only when I am at the bottom, it starts scrolling on the drawer.

- [x] SHOW THE FOOTER 
Keep the footer on top of the drawer for better navigation

### PR DESCRIPTION
**Pull request by giteshk11**
Fixes #185

### CODE REVIEW

**Review by paulchrisluke — APPROVED** [review]

**Comment by weareminigolf** [comment]
Not Sure I am looking at the right place for this  https://deploy-preview-198--weareminigolf.netlify.app/
But this issue still remain (as you can see, I did hole 2 (and it is active in the navigation path) But the score doesn't show in the table.
Capture

**Comment by paulchrisluke** [comment]
@weareminigolf give it a try now in a private browser, should be working

**Review by weareminigolf — COMMENTED** [review]
perfect!

**Comment by weareminigolf** [comment]
All scores now show immediately, that's perfect. 
I can't seem to scroll properly on the pop up though, this issue is "ticked" but it still doesn't work on my phone.

BTW: I can see also the scrolling of thenavigation path now works well, thanks a lot

**Comment by paulchrisluke** [comment]
@weareminigolf do you have a video of this error I can't re-create

**Comment by weareminigolf** [comment]
I sent it on fb messenger

**Comment by paulchrisluke** [comment]
@giteshk11 You're good to merge this PR. I made a new issue for the scroll issue since it's unrelated to this change

https://github.com/whynotearth/we-are-mini-golf-frontend/issues/204

**Pull request merged**
